apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.hello.service.type }}
  ports:
    - port: {{ .Values.hello.service.port }}
      targetPort: {{ .Values.hello.service.targetPort }}
      nodePort: {{ .Values.hello.service.nodePort }}
      protocol: TCP
      name: {{ .Values.hello.service.name }}
  selector:
    release: {{ .Release.Name }}
